<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<h3 class="page-header">Orders</h3>
	<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">
			
			<label class="control-label" for="formGroupInputSmall">Total:</label> Rs.<?php echo number_format($invoice['total_amount'],2); ?>
			<div class="clearfix"></div>
		</div>
		<?php if(!empty($invoices)) { ?>
		<!-- Table -->
		<table class="table table-bordered table-hover">
		<thead>
		<tr>
			<th>Sr. No.</th>
			<th>Invoice#</th>
			<th>Amount</th>
			<th>Customer</th>
			<th>Company</th>
			<th>Generated By</th>
			<th>Date/Time</th>
		</tr>
		</thead>
		<tbody>
		<?php $serial = ($pageNumber *  ($this->config->item('pagination')['per_page'])) + 1; ?>
		<?php foreach($invoices AS $k => $v){ ?>		
		<tr>
			<th scope="row"><?php echo $serial++; ?></th>
			<td><a href="/invoice/details/<?php echo $v['id'];?>"><?php echo $v['invoice_no'];?></a></td>
			<td>Rs. <?php echo $v['amount'];?></td>
			<td>
				<?php 
					if(!empty($v['customer_info'])){
						$customer = (array)json_decode($v['customer_info']);
						print($customer['customer_name'].'<br/>'.$customer['customer_mobile']);
					}else{
						print("N/A");
					}
				?>
			</td>
			<td><?php echo $v['company_name'];?></td>
			<td><?php echo $v['user_name'];?></td>
			<td><?php echo date("Y-m-d g:i a",$v['created_at']);?></td>
		</tr>
		<?php } ?>
		</tbody>
		</table>
		<div class="panel-footer"><div class="pull-right"><?php ($pagination)?print($pagination):""; ?></div><div class="clearfix"></div></div>
		<?php } else { ?>
		<div class="panel-footer"> <div class="alert alert-info" role="alert"><strong>No records available!!</strong></div> </div>
		<?php } ?>
	</div>
</div>